<?php
/** @var JackFlash\Blog\Block\Blog $block */
?>
<h3>Comment:</h3><br>
<form method="post" action="/blog/comment/create">
    <label for="article_id">Article:</label><br>
    <input type="number" id="article_id" name="article_id">

    <label for="author">Author:</label><br>
    <input type="text" id="author" name="author" maxlength="64"><br>

    <label for="content">Comment:</label>
    <input type="text" id="content" name="content"><br>

    <label for="url">Url:</label>
    <input type="text" id="url" name="url" maxlength="250"><br>

    <label for="enabled">Enabled:</label><br>
    <input type="checkbox" id="enabled" name="enabled" value="1"><br><br>

    <input type="submit" value="Submit">
</form>
