<?php
/** @var JackFlash\Blog\Block\Blog $block */
?>
<h3>Article:</h3><br>
<form method="post" action="/blog/article/create">
    <label for="author">Author:</label><br>
    <input type="text" id="author" name="author" maxlength="64"><br>

    <label for="title">Title:</label><br>
    <input type="text" id="title" name="title" maxlength="250"><br>

    <label for="description">Description:</label><br>
    <input type="text" id="description" name="description" maxlength="1024"><br>

    <label for="content">Content:</label><br>
    <input type="text" id="content" name="content"><br>

    <label for="url">Url:</label>
    <input type="text" id="url" name="url" maxlength="250"><br>

    <label for="status">Status :</label><br>
    <input type="checkbox" id="status" name="status" value="1"><br>

    <label for="enabled">Enabled:</label><br>
    <input type="checkbox" id="enabled" name="enabled" value="1"><br><br>

    <input type="submit" value="Submit">
</form>
