<?php
/** @var JackFlash\Blog\Block\Blog $block
 */

$tmp = $block->getDataArticle();
?>

Author:
<?= $tmp->getData('author') ?> <br>
Title:
<?=  $tmp->getData('title') ?> <br>
Description:
<?=  $tmp->getData('description') ?> <br>
Content:
<?=  $tmp->getData('content') ?> <br>
Status:
<?=  $tmp->getData('status')?> <br>
Url:
<?= $tmp->getData('url') ?> <br>
Enabled:
<?=  $tmp->getData('enabled') ?> <br><br>
