<?php
/** @var JackFlash\Blog\Block\Blog $block */
/** @var JackFlash\Blog\Controller\Index\Index $tmp */
?>
<h3>Article:</h3><br>
<form method="post" action="/JackFlash/Blog/Controller/Article/CreateArticle.php">
    <label for="author">Author:</label><br>
    <input type="text" id="author" name="author" maxlength="64"><br>
    <label for="title">Title:</label><br>
    <input type="text" id="title" name="title" maxlength="250"><br>
    <label for="description">Description:</label><br>
    <input type="text" id="description" name="description" maxlength="1024"><br>
    <label for="content">Content:</label><br>
    <input type="text" id="content" name="content"><br><br>
    <input type="submit" value="Submit">
</form>
